### ISSUE TITLE
Проверка 1

### ISSUE THREAD

**Issue by KseeBMSTU** [NikZheleztsov/DBMS#1]
- [ ] 1. Вывод списков дисциплин по факультетам через отдельные SELECT'ы к таблице кафедр и таблице организаций.
- [ ] 2. Выборка 2 берёт дисциплины по id, а не по названию
- [ ] 3. Проблемы с записью файлов
- [ ] 4. Без каскадного удаления

**Comment by NikZheleztsov** [comment]
Добрый вечер, Ксения Алексеевна.
 
Для облегчения и ускорения проверки добавил информацию в README.md, в котором представлена информация о всех командах, примеры их применения, а также соответствие между заданием и командой, которая его выполняет. Также добавил возможность писать скрипты (см. README). Написал скрипт по развертыванию экспериментальной БД (example_db.dbms).
*  Теперь можно получить общую информацию о факультете, используя faculty_info
*  По названию (любая команда, принимающая id, принимает и имя. Выборки (отдельные функции, не select) — только имена)
*  Их больше нет
*  Теперь есть каскадное удаление и каскадное сохранение любых выборок.   
>Вторник, 11 мая 2021, 15:31 +03:00 от KseeBMSTU ***@***.***>:
> 
> 
>*  1. Вывод списков дисциплин по факультетам через отдельные SELECT'ы к таблице кафедр и таблице организаций.
>*  2. Выборка 2 берёт дисциплины по id, а не по названию
>*  3. Проблемы с записью файлов
>*  4. Без каскадного удаления
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
----------------------------------------------------------------------
С уважением,
Железцов Н.
ИУ8-24

**Comment by KseeBMSTU** [comment]
Принято
